version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universaldb
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"

  java-backend:
    build:
      context: ..
      dockerfile: devops/docker/Dockerfile-java
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb

  php-backend:
    build:
      context: ..
      dockerfile: devops/docker/Dockerfile-php
    ports:
      - "8081:80"
    depends_on:
      - mysql
      - mongodb
