apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
        - name: java-backend
          image: your-dockerhub/java-backend:latest
          ports:
            - containerPort: 8080
